### ISSUE TITLE
PowerBI instructions conflicts

### ISSUE THREAD

**Issue by meghanls** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#111]
# Module: 
#### Step: 14

When I attempt to complete the step as described, I get this error: "The name 'Building' is already used for a column on table 'lh_problemreport'. Choose a different name." This error is logical to me because I see there already is a column named Building in my lh_problemreport table.

![renameColumnError](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/133369896/e926f20d-2559-4d7d-87a7-52ecbae4b8fe)

However, if I rename my new column (to BuildingNew), I get this error: "The column 'lh_Building[lh_name]' either doesn't exist or doesn't have a relationship to any table available in the current context." (See second screenshot.)

![noRelationship](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/133369896/eb759c8e-98f8-4231-abc1-696f84f28208)

Looking ahead, I see a similar problem will be experienced in Step 15.

For Step 16, I anticipate a problem because I don't have an lh_problemreportid column in my lh_problemreport table, but I *do* already have a column called Problem Report (which is what I'm supposed to rename my lh_problemreportid column.)

For Step 17, I anticipate a problem because while I *do* have a statuscodename column in my lh_problemreport table, I also already have a Status column (which is what I'm supposed to rename my statuscodename column.)

**Comment by zixuansunnydeng** [comment]
I feel 'Building' already exist on table 'lh_problemreport maybe the one we require to create. idk

**Comment by DanePillay-nel** [comment]
How is this closed as solved when this problem still exists in the instructions?
