### ISSUE TITLE
Not sure if issue or not, the "Location" and "Department"  field in the apps.

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#128]
I'm not sure if this is an issue or not...  I'm referring to the "Location" and "Department" fields in the Problem Reports table.

In the Model-driven app (Lab 2.1), the Form has two "halves"... the top half shows the Title, Owner, Building, Location, Details and Photo.  The bottom half shows the "Resolution Details" with the fields Department, Status Reason, etc.

Then in the Canvas app, where an end-user would be creating a new ticket, the Lab (lab 3.2) has you remove the Location field and add the Department field.

However - shouldn't the end user be adding the Location of the problem, and NOT adding the Department?  I thought the Department field would be edited by Maintenance in the Model-Driven app.

**Comment by ephiax20** [comment]
https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/blob/master/Instructions/Labs/lab03-2-canvas-app.md#:~:text=Remove%20the%20Location%20Column

**Comment by ephiax20** [comment]
Thanks for raising this, I'll escalate with the Course Content Developer.

**Comment by tylerfarmer1** [comment]
Simon - I have a lot of feedback on this course.  Not "issues" that need to be opened, and not "bad" things either...It's that I've taught this course 7 times, and there's a lot of feedback that I think could help with evolution of this course.  If there's a way to provide that feedback, like a short 15 minute call, I would welcome the opportunity to help.  Email of course is possible, but it's more complicated than I could describe in an email.

**Comment by arnoldvilleneuve** [comment]
@tylerfarmer1 Hey Tyler, I teach this course as well. Have taught it at least a dozen times. I am not involved with Microsoft course development but I personally as an MCT would love to hear your comments and experience about what works for you in delivering PL-100. I am teaching it for the next three days and would love your insight. 

Arnold dot Villeneuve@rogers dot com    

Drop me an email and we can connect on a call. 

Looking forward to speaking with you. 

Arnold

**Comment by ephiax20** [comment]
Hi, thank you for the kind offer - I will pass on your comments to the relevant Course Developer.  There is the MCT Lounge available as well, https://aka.ms/mctlounge
