### ISSUE TITLE
1 environment variable needs to be updated. 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#131]
# Module: 2.1
#### Step: 00

Description of issue

ImportData.zip spawns 1 environment variable needs to be updated. 

Repro steps:

![PL-100 1 environment variable needs to be updated](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/1082625/2b730585-099e-41b6-8a95-bb2c3d05d0d0)

**Comment by ephiax20** [comment]
Hi @arnoldvilleneuve I don't think this is part of the DataImport.zip and possibly unrelated, please can you select the '1 environment variable link' on your environment and take a screenshot of which environment variable it is, what is the name etc. ?

**Comment by ephiax20** [comment]
Is it called "Working Solution" ??

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/116392278/76e09c90-2140-47a9-8450-b84c29a9277d)

**Comment by ephiax20** [comment]
Possibly related: https://arunpotti.com/2023/06/10/what-is-microsoft-dataverse-accelerator/

https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Update-of-an-Environment-Variable/td-p/2372821

**Comment by arnoldvilleneuve** [comment]
To late. It simply ask you to put in a name. I used lh for lamna healthcare and the error went away. Not sure either if it is related to dataimport.zip or having built the solution.

**Comment by ephiax20** [comment]
Hi, I think this is related to the Dataverse Accelerator app, I replicated it this way and thus unrelated to the Instructions, this can be safely ignored.
