### ISSUE TITLE
Power Platform Start Free subscription process does not work most of the time

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#134]
# Module: 00
#### Step: 00

Description of issue - This process fails for most of the students. Skillable provided a workaround which I have attached. This has been a known problems for months now. 

[PL-100 Start Free Instructions.docx](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/files/12833943/PL-100.Start.Free.Instructions.docx)

Exercise 1 – Acquire a Power Platform trial tenant
Navigate to https://powerapps.microsoft.com/ and select Start free.

Enter the email address from the provided Microsoft 365 credentials. Agree to the terms & conditions then select Start your free trial.

You will see a prompt that you have an existing account with Microsoft. Select Sign in.

Enter the password provided by the Authorized Lab Hoster.

Select Yes to stay signed in.

If applicable, read through the prompts by selecting Next, then select Let's Go.

Note: If you encounter an error: "Sorry, there's been a disconnect", you can follow the steps below. If not, you can continue to Exercise 2.

Navigate to https://make.powerapps.com/.
Select the Gear Icon (Settings) from top-right corner on the header of the page.
Select Plan(s) and verify if you have Power Apps Per User Plan Trial.
If you do not have the above license, repeat Exercise 1. Otherwise, proceed to Exercise 2.

Repro steps:

1.
1.
1.

**Comment by ephiax20** [comment]
Hi, are you seeing the "Sorry, there's been a disconnect" error for most of the students?

How many??

**Comment by ephiax20** [comment]
In replicating this, I think there has been a change in the type of Environment created when you follow the Start free trial steps. A 'Developer' style environment is now created. There is a new step introduced, with a new choice, **Start building apps** this wasn't there before.

Now, after creating the 'Developer' environment, it is not possible to create another Trial or Production environment:

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/116392278/76afbea3-f0ed-4c35-a786-a0659237e169)

**Comment by ephiax20** [comment]
This issue also breaks the Test & Deploy module which currently creates a new Dev environment, which is no longer possible.

**Comment by arnoldvilleneuve** [comment]
Nicely done and well-researched. Thank you Simon for your time on this. 

I still believe the work around provided for PL-200 and PL-400 is the way to go and the method I will be using going forward until this issue is fixed. 
[PL-100 Start Free Instructions.docx](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/files/12869707/PL-100.Start.Free.Instructions.docx)

**Comment by ephiax20** [comment]
I even had a different issue with the workaround yesterday, but it is working for me now.  I probably could've signed out and back in again or similar.  I'll check first but we can probably include this workaround in the actual instructions as I don't see any other fix for this.

**Comment by arnoldvilleneuve** [comment]
Thank you for all your efforts on this Simon. It is appreciated. 
Arnold Villeneuve 613-833-0984 

    On Wednesday, October 11, 2023 at 10:38:25 a.m. EDT, Simon E ***@***.***> wrote:  
 
 


I even had a different issue with the workaround yesterday, but it is working for me now. I probably could've signed out and back in again or similar. I'll check first but we can probably include this workaround in the actual instructions as I don't see any other fix for this.

**Comment by arnoldvilleneuve** [comment]
10 am on the morning of the first day of class when we are trying to get all of the students successfully started is not the time to be doing A-B Testing! 
Arnold Villeneuve 613-833-0984 

    On Thursday, October 12, 2023 at 10:29:22 a.m. EDT, Simon E ***@***.***> wrote:  
 
 


This looks like a gradual roll out or A-B testing, I am not seeing this "Start building apps" button in other courses. I just did the same set up for PL-900 and it worked fine. Puts us in a tricky position for the instructions.

**Comment by ephiax20** [comment]
I have retested the existing instructions for PL-100 Lab 0 validating the Lab environment again today, in Skillable. No issues in following and creating a Trial environment now, looks like this issue has been resolved.   I will close this issue but please re-open or log a new one if you experience any issues in future.
