### ISSUE TITLE
Power Automate

### ISSUE THREAD

**Issue by Gayatrimurali** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#142]
# Module: 004
#### Step: 012

Description of issue : Status Reason and Resolution not coming as expected.

Repro steps:

1. After making changes in the flow as per ex-03; task-02, we are increasing the cost to 1000$ and more
1. Receiving the message on teams to approve/reject, after clicking on reject
1. Not able to find the **response summary** in resolution and status reason isn't changing to Won't fix
![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/139850907/052853c3-56b6-4370-bdad-c17b400e368c)
@georged @seesharprun @GraemeMalcolm @jhcg @LaurieHeer please revert back as soon as possible.

**Comment by ephiax20** [comment]
Hi @Gayatrimurali can you share the Flow Run from the 28-day flow run history of the **Escalate Expense Approval** cloud flow?

**Comment by ephiax20** [comment]
@Gayatrimurali I'm afraid I am unable to replicate the issue following the instructions, I see the Response Summary as expected.

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/116392278/71a2de4d-3e55-4109-ae96-d55f1456d975)

**Comment by Gayatrimurali** [comment]
> @Gayatrimurali I'm afraid I am unable to replicate the issue following the instructions, I see the Response Summary and Status Reason updated by the Flow as expected.
> 
> ![image](https://user-images.githubusercontent.com/116392278/281758412-71a2de4d-3e55-4109-ae96-d55f1456d975.png)

Could you please let me know if the response of the flow sent by you is after rejecting from teams or power automate? @ephiax20

**Comment by ephiax20** [comment]
Let me check it via Teams.

**Comment by ephiax20** [comment]
Hi, I found the issue.  Will be amending the earlier Flow/ Teams adaptive card instructions now to resolve this.

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/116392278/ef2eab82-3893-4f99-a8f1-a369231a7fca)

**Comment by Gayatrimurali** [comment]
> Hi, I found an issue. Will be amending the earlier Flow/ Teams adaptive card instructions now to resolve this.
> 
> ![image](https://user-images.githubusercontent.com/116392278/282059159-ef2eab82-3893-4f99-a8f1-a369231a7fca.png)

Sure, thankyou!
