### ISSUE TITLE
LAB-07: Test & Deploy

### ISSUE THREAD

**Issue by Gayatrimurali** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#145]
# Module: 007
#### Step: 011

Description of issue: Receiving a dependency error.

Repro steps:

1. **PRE-REQUISITE UPDATE :** According to lab guide, the pre-requisite has been mentioned as lab2.1, but we cannot test lab-09 without creating canvas app (lab3.2) as we are using the NEW REPORTS TAB in exercise-03 of lab-07 (**please look into it**)
1. **ISSUE:**  Performed the [lab-07 and in exercise-04](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/blob/master/Instructions/Labs/lab07-test-deploy.md#exercise-4-import-export) exported and downloaded both managed and unmanaged files from AJ practice as per the instruction.
1. Created a new environment to import the managed solution file but we are facing a dependency error as shown in the below screenshot. We tried importing the canvas app and table manually into the new environment but still facing the same error while importing the solution.

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/139850907/53a82985-5f85-47e7-b7b5-eba34e180a16)

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/139850907/40969d65-db34-4167-9f03-eb0268c7c9dc)

**Comment by ephiax20** [comment]
Hi @Gayatrimurali from the error you have shared, it seems the missing dependency is the 'Shared Components', from Lab 3.02 - Please can you first import the [Shared Components 1.0.0.4](https://github.com/ephiax20/PL-100-Microsoft-Power-Platform-App-Maker/blob/master/Instructions/Labs/03-2/Resources/SharedComponents_1_0_0_4.zip) and try again?

**Comment by Gayatrimurali** [comment]
Hi @ephiax20, we have performed the lab-3.2 and proceeded with lab-07. Also, had imported the **shared components 1.0.0.4** but still facing the error.

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/139850907/00cb8136-2433-4468-89e6-14042d005c4e)

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/139850907/02e331be-bca6-4b35-83fe-42a2504c5732)

**Comment by ephiax20** [comment]
@Gayatrimurali have you first imported the Shared Components into the **new** environment? I believe this is the dependency that's missing from your solution and causing this error.

**Comment by Pranjali-9999** [comment]
Hello @ephiax20  , I am also facing the exact issue on Lab 7 what @Gayatrimurali is facing while importing the solution on new environment that is devone which we created as per given 
![Showing Issue](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/150769167/91754b57-8aa4-4848-8d50-6155eaa35d31)
instructions.

**Comment by ephiax20** [comment]
I'm investigating this. I have been able to replicate..

**Comment by Gayatrimurali** [comment]
Hi @ephiax20, any updates/solution on the dependency error?

**Comment by ephiax20** [comment]
Hi, I don't think there is a quick fix or workaround for this.  The issue is the way the Shared Components are used in this Lab.

**Comment by chandlersyal** [comment]
We will make sure the dependencies are dealt with in the Jan 2024 update that is currently underway.
