### ISSUE TITLE
Lab 00: Ex 1 trial steps do not match current behavior; Ex 2 Trial-type env not allowed by license

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#147]
- Module 0: Course introduction
- Lab 00: Validate lab environment
- Exercises 1 & 2

Similar to the previous report in #134, we have observed that the steps required to begin a Power Apps trial are now somewhat different from those specified in Ex 1. More critically, the trial that is provisioned does not support the creation of a Trial-type environment as required by Ex 2 currently.

In our testing, a Developer-type environment was possible to create instead. However, we have not evaluated the suitability of creating this type of environment for the whole of the subsequent lab activities.

Starting from Ex 1 step 1 and continuing as prompted, these were the steps followed to start a trial in our testing:

1. Navigate to https://powerapps.microsoft.com/
2. Select Try free [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/7cec9896-4ab7-4771-90bd-057267c16342)
3. Select Start building apps [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/89d19b26-1098-4c61-97ba-131286c0946d)
4. Enter lab tenant admin email [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/d1dcd445-2deb-490a-9518-4829c026d0e6)
5. Select sign in [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/21618898-340b-4d28-bf18-b50cafbedc5f)
6. Enter password, select Sign in, select Yes [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/3de6a7fe-ac46-4124-8be7-bed668754d60) [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/33ea2807-00d8-4b4c-b81f-655d0cea40aa)
7. Enter 0123456789 under business phone number and select Get Started [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/ea38810d-4caf-421b-8e7f-b52b96e6542b)
8. Select Get started [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/cc5e3c6d-6543-4352-baed-59faac6dd37b)
9. In Power Apps | Home tab that opens, enter phone number 0123456789 and select Submit [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/c239a040-5c15-4207-aa55-b99ae45a889b)
10. Done at the Power Apps | Home page [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/cf4da634-e1e6-4a5f-b516-447363fc6f5a)

The license name visible from the Power Apps home page seems to now be "Power Apps Community" ([Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/39cf88fc-dc58-4055-b98f-9e56cc8a006e)). The license when viewed in the 365 admin center is displayed as "Microsoft Power Apps for Developer" ([Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/59e1c95d-c4ae-4451-92b9-4011c0bc0002)).

In Exercise 2, an environment with the type Trial could not be provisioned with the license obtained as above. The below message was displayed.

> The licenses assigned to this user do not allow creation of a Trial environment. Create a Production environment to continue or contact your administrator for further instructions.

![Screenshot 2023-11-27 135707](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/fb73e4f7-1511-4f99-927a-697237335851)
![Screenshot 2023-11-27 135718](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/d9a77ed5-283c-42a5-8834-51b22c429666)

A Developer environment was created successfully.

[Screenshot1](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/62fcf956-4c9b-4f4b-a96a-f9d67c9da3bb)
[Screenshot 2](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/aeb2932d-9e28-44a7-b0d0-efa26c321e87)
[Screenshot 3](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/7d3fa172-01c3-460e-bf47-4af5852c9571)
[Screenshot 4](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/5e4aec2e-a7c1-4f1e-97e9-e8ab6dd063bc)

Currently, the lab cannot be completed as the required Trial environment cannot be created with the provisioned license. Updating the lab to use a Developer environment or to obtain a different license by some other means may resolve the issue.

**Comment by SkillableMG** [comment]
An additional note regarding the workaround of provisioning a Power Apps Premium trial through the 365 admin center, as mentioned in https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/issues/134#issuecomment-1757580320: this method is not currently likely to be suitable for labs as a credit card is now required.

[Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/d78ba74d-d823-4ae3-ae1e-a2ae3219f9a5)


See also https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/issues/97

**Comment by SkillableMG** [comment]
A slightly different method for obtaining a Power Apps trial license compatible with a Trial-type environment was verified today. The main difference from the tested method listed in the first message above is the selection of the "Start using apps" rather than the "Start building apps" button at step 3 above.

3. Select Start using apps [Screenshot](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/89d19b26-1098-4c61-97ba-131286c0946d)
4. Enter lab tenant admin email [image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/4a2ae0ca-1a63-48bf-be47-2e920cfd742f)
5. Enter password, stay signed in [image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/50201730-463b-41b6-b24c-2abb09e5e797)
6. Power Apps | Home loads in the same tab, enter 0123456789 in the phone number field and select submit [image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/4e36a5d6-13cc-4944-a5fe-03e7fee55a15)
7. Done, on Power Apps | Home

Trial license is displayed under the Power Apps home Plan(s) pane as "Power Apps Per User Plan trial".

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/46fe481a-3191-492b-98d8-cb89f2c07d4f)
 
Under the 365 admin center, "Microsoft Power Apps Plan 2 Trial"

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/5fbea429-dce1-4dd1-b104-39c8054d1bd2)

For comparison, PL-900 instructions were updated this month to use the "Start using apps" route (https://github.com/MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals/commit/48f14c245ff92e8e4d50e2cfc0a9e9d6885bad63).

Suitability of this approach for lab activities has not been tested past the successful creation of a Trial-type environment as per Lab 00 Ex 2.

**Comment by ephiax20** [comment]
@SkillableMG Something further to note: In testing around this issue, I do not **always** see the screen with the "Start using apps" and the "Start building apps" buttons.  It seems that this functionality is on a gradual or phased rollout, which makes updating the instructions difficult. It's not just a simple workaround as it doesn't always show like this, but we do need to put a warning in.
