### ISSUE TITLE
PL-100 Code and Flow run issue

### ISSUE THREAD

**Issue by officialAY** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#152]
# Module: 01 - 03
#### Step: 10-17

Description of issue:
This issue involves the flows always failing at the initial run, and we had to run it multiple times for it to work, issue with the Table ID from the "Input Data" not matching the destination.

-- Also, there are issues on the code for Lab 03-1 (Canvas Apps in Teams), the codes are outdated in the use, calling [@Availabilty] throws error, what works is to called the nested information 'Availability(Gadgets)', and this is what solves the issue.

Repro steps:

1. For the flow, employ the use of retry logics to get the flow to work.
2. For the Canvas Apps in Teams code, changed the initial code from [@Availabilty] to 'Availability(Gadgets)' to resolve the issue.

Kindly help clean this up.

**Comment by ephiax20** [comment]
Hi, the **Availability** choice column in the Gadgets table must be synced with a Global choice column called Availability for this to work.

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/116392278/f1afe214-2d9d-4ed1-b8b9-a0add1391f73)

However, it seems the UI does not present the sync global choice as an option when you initially create a New column of Choice Data type, during the table creation. However, it does show if you later go back and try to add a new column. I will investigate this further to confirm and make recommendations.

Using ```Availability (Gadgets)``` doesn't work either, you will receive an error incompatible types trying to compare the OptionSet with Text. But as a workaround to this, you could use ```Filter(Gadgets, Text(Availability) <> "Picked up")```
Note: This will show a Delegation warning, but it will work as expected in this case as the data set is not large.

**Comment by ephiax20** [comment]
Yep, on further review this is because you cannot Sync to a Global Choice before the Table is actually created.

The solution will be: We need to move the Availability column creation to the next task, after the table has been created.
