### ISSUE TITLE
I feel 'Building' already exist on table 'lh_problemreport maybe the one we require to create. idk

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#154]
I feel 'Building' already exist on table 'lh_problemreport maybe the one we require to create. idk

_Originally posted by @zixuansunnydeng in https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/issues/111#issuecomment-1826734468_

**Comment by DanePillay-nel** [comment]
This issue was closed as completed but not resolved. The issue still exists in the lab instructions.
PowerBI instructions conflicts #111
 "The name 'Building' is already used for a column on table 'lh_problemreport'.

**Comment by chandlersyal** [comment]
new labs are being merged tomorrow and address this issue. Thank you!
