### ISSUE TITLE
Inaccurate guide

### ISSUE THREAD

**Issue by J0eGos** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#156]
# Module: 7.01

Description of issue:
The guides for this module seem very off, the start of the guide has the user navigate to the web app version of PowerBI yet the following screenshots are from the desktop app and do not match. This is also the case for some of the steps, they appear to be written with the desktop app layout in mind but intended for use on the web app.

In the same task are steps relating to workspaces and dashboards, which are only found on the web app version of PowerBI. However, the instructions are again intended for the PowerBI desktop app whenever the user is editing the report.

Here you can see the step asking the user to select report view, with a screenshot depicting the desktop app. Report view is not an option in the web app.
![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/128402777/f41a0f7b-8ff1-46a2-83d7-9d96d303f660) 

Please can we get some clarity on this as it is confusing instructors and students. 
Overall experience with the new guides is mixed depending on the module.

**Comment by chandlersyal** [comment]
Just pushed an update for the Power BI lab - please let me know if there are any further issues. Thank you for raising the issue!
