### ISSUE TITLE
Lab 4.4 - Type-O

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#157]
# Lab 04.4 - Create business process Flows and Business Rules
#### Step: 37

Description of issue

The instructions say to set this as "Business Required" but that is for Step 33.  Step 37 should be "Not Business Required."

And the picture for Step 38 is not 100% correct, the green box should have a correct label.

**Comment by chandlersyal** [comment]
Thank you! Fixed these.
