### ISSUE TITLE
Lab 06.1 Ex 2: Escalate Expense Approval flow fails `"Attribute 'lh_resolvedon' cannot be NULL"`

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#159]
- Lab 06.1: Create Power Automate flows
- Exercise 2: Build escalation flow
- Task 3: Test flow
- step 11

Problem report row does not update Status Reason and Resolution fields after rejecting approval. The Escalate Expense Approval flow fails with an error message `"Attribute 'lh_resolvedon' cannot be NULL"`. The Resolved On field is likely required due to the "Resolved on rule" created in Lab 04.4, Exercise 2.

![Screenshot 2024-02-19 094946](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/d9f86ea2-8845-4e01-b8e4-e83c32ed118c)

Editing the Escalate Expense Approval flow action "Update a row" to set the Resolved On field from the approval Completed On date allowed the flow to succeed. This addition could be specified near the previous Task 2, steps 41-42 to resolve this issue.

![Screenshot 2024-02-19 095226](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/2e740752-276d-4495-82ac-8d9ed30f6906)

 ![Screenshot 2024-02-19 095720](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/134323425/c90f0806-405e-4877-b3c0-dae7c40d9644)

Repro steps:
1. Complete Lab 06.1 prerequisites and Lab 04.4
2. Complete the above-referenced step
3. Observe lack of row update and failed flow

**Comment by SkillableMG** [comment]
The "Resolved on" value may also need to be re-added at Lab 06.1, Exercise 3, step 34 when editing the existing flow in Power Automate.

**Comment by tylerfarmer1** [comment]
I agree; I add a "step 41 1/2" where I have the student add utcNow() on the Resolved On field.
