### ISSUE TITLE
Lab 04.1, Task 2 outdated screenshot or accidental table

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#165]
Lab 02.1, Task 4, Step 5, assigning the related table of the new Assign to column you're creating causes a new User table to appear under All [p1]. This doesn't replicate for creating a new table when you do the same for Building in step 7. It doesn't seem to be intended, as Lab 04.1, Task 2 has you only with 3 tables [p2]. 

Can you please confirm if there are only supposed to be 3 tables, and the table creation for Users is incorrect? Or if the screenshot is outdated and needs to be updated?

[p1]

![image-1](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/94069201/15a771f7-2377-4b25-8491-b81444db2dcf)

[p2]

![image-1](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/94069201/95b6db6f-6776-4e57-afff-3dc8bf27db8d)

**Comment by ephiax20** [comment]
The screenshot [p2] looks correct, it's showing three different types of Information **Form**, not the tables.  It is correct for the User table to be included in the Solution.
