### ISSUE TITLE
Missing Screenshots in new lab

### ISSUE THREAD

**Issue by QAJaneHowell** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#20]
# Module: 03
#### Step: 02

Description of issue
The screenshot is missing there is just a place holder describing the screenshot that should be there. 

This repeats throughout this lab.

Please provide the screenshots!

1.
1.
1.

**Comment by JBJ2110** [comment]
HI--I found the screenshots in the relevant lab folders, but I would agree that they should be present in the lab. I am not sure if this is just something instructors are experiencing or students are as well?

**Comment by TesterTesterson1004** [comment]
This may have been an ALH/platform-specific issue, can you refresh the instructions of any existing labs (or start new ones) and re-verify?

**Comment by skulthm-ms** [comment]
It seems to be working now. I believe the images path had an issue and it got resolved.

**Comment by JBJ2110** [comment]
I was using the lab this afternoon and the issue was still present. I’ll check tomorrow am. 

Cheers! Jessica
