### ISSUE TITLE
Lab 3.2 Ex 7

### ISSUE THREAD

**Issue by instructor001** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#21]
Module 3
Lab 3.2
Task 7
Ex-7

Description of issue

Lab 3.2 - Exercise 7: Embed canvas in model-driven app does not work. Everything else works fine
Repro steps:

1.Lab 3.2 - Exercise 7: Embed canvas in model-driven app does not work. Everything else works fine.

**Comment by ChRocheFR** [comment]
It is only a lack of instructions. When in classic mode, on the Field Property popup, you have to specify that the Canvas App will be used at least in Web Mode (I choose Tablet too).

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review confirms this Issue.

**Comment by skulthm-ms** [comment]
Thank you instructor001 for your feedback. We have addressed this issue so I am going to close this. Please continue reporting any issues you may discover in the future.
