### ISSUE TITLE
Lab 03-2, Exercise 2 - My reports, Task: 1: Add gallery, Step 5 - error "Distinct is not allowed..."

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#23]
# Lab/Demo: 03-2
#### Step: 5 - Select the My Reports view you created for View.

Description of issue
When I select "My Reports" in Views, the gallery control will show an error: 
The requested operation is invalid. Server Response: Problem Reports failed: Distinct is not allowed when image attributes are selected.

The Items formula became: Filter('Problem Reports', 'Problem Reports (Views)'.'My Reports')

If in Views I will let "None" I could see all the records.

Repro steps:

The same as lab steps.

![Lab03-2-Problem](https://user-images.githubusercontent.com/32492990/142941710-19a39bd8-9b67-42df-8253-a734532b8b49.jpg)

**Comment by luconsta** [comment]
Digging more deeper, it seems that could be a "bug" in Power Apps, because I saw other reports ([unrelated to this class](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/BUG-Can-t-use-a-view-of-a-table-that-contains-image-fields-in/idi-p/1333917)) and changing the Layout of the gallery to any other option that will not include an image will work.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review confirms this Issue.

**Comment by skulthm-ms** [comment]
Thank you luconsta for reporting the bug. We will address it in very soon.

**Comment by skulthm-ms** [comment]
Thank you for reporting. We just made updates, and this issue should be resolved now.
