### ISSUE TITLE
Navigate is not permitted Error

### ISSUE THREAD

**Issue by J-O-S-H-C** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#29]
#### Step: 09

Description of issue:
![image](https://user-images.githubusercontent.com/39581053/149230931-d5a5baf5-e4c3-4222-9d52-9413c63e5d60.png)

According to standard practice, we create an app, check for the errors, and if there are none we publish it. After writing the formula, an error occurs, which means that functionality will not work.

Either there should be a way to include the formula so that we don't get an error, a modern, error free, formula should be used, or the step should be removed from the lab.

![image](https://user-images.githubusercontent.com/39581053/149230994-e4f2ca34-1664-4ce7-a306-87551ad94a55.png)

Thank You for all you do.

**Comment by skulthm-ms** [comment]
Thank you J-O-S-H-C. We really appreciate you filing these issues. We are going to investigate and remedy this.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #53.
