### ISSUE TITLE
Update the screenshots to the current features - Feature request 

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#30]
# Module: All
### Task: All

Description of issue

Screenshots are not up-to-date. Few features have been changed and required to be referred through a correct screenshot. 

Repro
1. Module 2 - Lab 2.1 - Exercise 2 - Task 1 - Step 3
2. 
![M2_L2 1_E2_T1_S3_Screenshotsincorrect_SaveandCreate](https://user-images.githubusercontent.com/92770552/150656094-bf8b80aa-5dc2-408e-9d2a-d0fafd2bad7f.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
Thank you ParamRamki, we will address this screenshot issue in our next update.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
Thank you for reporting. We just made updates, and this issue should be resolved now.
