### ISSUE TITLE
Entity is still shown instead of Table

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#31]
# Module: 2
#### Step: 12

Description of issue

Instruction is to 'Select 'Entity' for  'Content Type' and  'Problem Report' for 'Table'. Whereas the 'Entity' has been renamed to 'Table' and if you could refer the screenshot there is no 'content type' it just says 'Type' in the Powerplatform app. 
Repro steps:

1. Module 2 - Lab 2.1 - Exercise 4 - Task1 - Step#12 

![L2_E4_T1_S12_Labenv_entity](https://user-images.githubusercontent.com/92770552/150656402-1553c0c2-1305-4d93-8f7c-f95982c1aed8.png)

![M2_L2 1_E4_T1_S12_LabInstructions_Entity4Table](https://user-images.githubusercontent.com/92770552/150656509-e217db81-063d-49c4-acec-3a8b1fbfe470.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this is no longer an issue.

**Comment by skulthm-ms** [comment]
Thank you ParamRamki. We have addressed this issue so I am going to close this. Please continue reporting any issues you may discover in the future.
