### ISSUE TITLE
Delegation Warning Error thrown

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#32]
# Module: 3
#### Step: 19

Description of issue
Throwing a warning sign that 'Delegation Warning: The "CountRows" part of this formula might not work correctly on large data set'.  DisplayMode of the Next icon: If(currentIndex = CountRows([@ModelDrivenFormIntegration].Item.'Problem Reports'), DisplayMode.Disabled, DisplayMode.Edit)

Repro steps:

1. M3-L3.2-T3-S#19: throwing Delegation warning

![L3 2_E7_T3_S19_Delegationwarning](https://user-images.githubusercontent.com/92770552/150656907-ffa4aa3e-4c25-47a9-967d-e7b3c44f6e7c.png)

**Comment by skulthm-ms** [comment]
Thank you ParamRamki, we will investigate and get back to you.

**Comment by skulthm-ms** [comment]
Thank you for reporting. We just made updates, and this issue should be resolved now.
