### ISSUE TITLE
DirectQuery option not appearing

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#33]
# Module: 5
#### Step: 05

Description of issue

Instruction is to select the 'DirectQuery' which is not found in the lab environment

Repro steps:

1. M5-L5-E1_T2_S5

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
Thank you ParamRamki, we will investigate and get back to you.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review confirms this Issue.
