### ISSUE TITLE
Import file failed company 311 in the new environment created

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#36]
# Module: 6
#### Step: 18 - 20

Description of issue

Import file failed company 311 in the new environment created.

Repro steps:

1. While performing the Click 'Import' file, its keep failing.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
Thank you ParamRamki, we will investigate and get back to you.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by ScuderiNYC** [comment]
I;m receiving a message at teh same sep that states there are missing dependencies.

**Comment by skulthm-ms** [comment]
Thank you for reporting. We just made updates, and this issue should be resolved now.

**Comment by LourdesBellR** [comment]
Hi. Me and another person, have the same problem of "are missing dependencies: Problem resolution process (lh_problemresolutionprocess) and Lamna Healthcare Shared Components (lh_lamnahealthcaresharedcomponentsa_56f77)"
