### ISSUE TITLE
Lab04 Task-1 Outlook connection issue

### ISSUE THREAD

**Issue by vishalsalvan** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#37]
# Module: 04
#### Step: 21

Lab04 Task-1 Outlook connection issue

Repro steps:

1.
1.
1.

**Comment by skulthm-ms** [comment]
Thank you vishalsalvan, we will investigate and get back to you.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by skulthm-ms** [comment]
Closing as we don't experience this issue. Please try again and if the issue persists please reach out again with more details if possible so we can regenerate the issue to provide a fix.
