### ISSUE TITLE
Display Name should be Title and not Display Name

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#45]
# Module: Lab 02.1: Data model and model-driven app

#### Step: 09

Description of issue
9. Enter Problem Report for Display name, on the Primary Column tab, enter Display name for Title.

should be

Enter Problem Report for Display name, on the Primary Column tab, enter Title for Display name.

in order to match picture 

Repro steps:

1.
1.
![pl-100 lab 2 ex 2 step 9 error 1](https://user-images.githubusercontent.com/1082625/155437573-a73b1b4d-4f4d-4ed2-a3fc-e86456cf4d7a.png)

1.

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We just got it fixed.
