### ISSUE TITLE
General list of found issues in the whole labs guidance

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#5]
Lab 2, Exercise 6: Import data
1. The solution import is now completely migrated to the modern UI and is asynchronous. The steps need to consider this, so that after the import process is triggered, the students need to wait until a message will tell them, that the import was successful. After that, they need to publish all customizations
2. The first opening of the flow, when the connection is shown, needs the description of the additional steps to authenticate the connector (click on the + sign and go through the authentication dialogue)

Lab 3, Exercise 1: Create canvas application
1. The solution import description needs to be modified the same way as in the previous

Lab 3, Exercise 2: My reports
1. The Tab control from the gallery does not have the orange background color as illustrated but a white

Lab 3, Exercise 3: Allow removing reports
1. Task 1, Step 1 is misleading, there should not be a new gallery inserted

Lab 3, Exercise 4: Add new report
1. Task 22 does not make any sense

Lab 3, Exercise 5: Test the application
1. When selecting an image, this is sometimes shown on the New Reports Screen rotated by 90 degrees. On the Main Screen however, the image is OK

Lab 4, Exercise 3: Test processes
1. This is just a suggestion, not an issue: Instead of "clicking" on the BPF stages, use the proper method of using the "Next stage" button

Lab 5, Exercise 2: Build escalation flow
1. Task 2: Build escalation flow, Step 42: The value "Response summary" does not bring in the required text "We don't have the funds for this item" into the CDS record, rather a real summary of the request. A different dynamic value must be used instead.
2. Task 3: Test flow: Steps 5 - 6: There should be a warning, that an approval flow runs very slowly and the approval request can take up to 60 minutes to arrive

Lab 5, Exercise 3: Send approval requests as adaptive card in Microsoft Teams
1. Task 2: Build escalation flow, Step 29: The value "Response summary" does not bring in the required text "The item is too expensive" into the CDS record, rather a real summary of the request. A different dynamic value must be used instead.

Lab 7, Exercise 1: Create security roles
1. Task 1: Create security roles: Step 11 is unclear. What is "Associate Model-driven app with the Company 311 Admin role."

Lab 7, Exercise 1: Exercise 2: Solution checker
1. Task 1: Run solutions checker: Step 2 needs to be corrected, so that the Company 311 solution must be selected first, only after that the solution checker can be started

Lab 7, Exercise 4: Import export
1. Task 2: Create new environment and import solution: The step 6 needs to be removed

**Comment by dbarker19** [comment]
Lab 3, Exercise 2: My reports
The Tab control from the gallery does not have the orange background color as illustrated but a white.
* If this is not fixed in the control you can add a step to have the students fix that fill color before using the control.

Lab 5, Exercise 2: Build escalation flow
Task 2: Build escalation flow, Step 42: The value "Response summary" does not bring in the required text "We don't have the funds for this item" into the CDS record, rather a real summary of the request. A different dynamic value must be used instead
* This should be the "Response Comment" dynamic value.
Task 3: Test flow: Steps 5 - 6: There should be a warning, that an approval flow runs very slowly and the approval request can take up to 60 minutes to arrive
* I received and email almost immediately and chose reject. I didn't wait to see how long it would take for it to show up in "Power Automate, Approvals, received" so maybe change the directions to have the user check the email and then go check the sent and history under "Power Automate, Approvals"

Lab 5, Exercise 3: Send approval requests as adaptive card in Microsoft Teams
Task 2: Build escalation flow, Step 29: The value "Response summary" does not bring in the required text "The item is too expensive" into the CDS record, rather a real summary of the request. A different dynamic value must be used instead.
* This should be the "Response Comment" dynamic value.

All the other items in the list do need to be corrected.

**Comment by DanePillay-nel** [comment]
lab 71.	Task 1: Create security roles: Step 11 is unclear. 
What is "Associate Model-driven app with the Company 311 Admin role."

**Solution**
Steps. go to your solution Company 311
	->Select Company 311 Admin(Model driven app)
	->click more options ... and select share
	->select app and then from manage roles on right search for 
	company 311 admin role.
	->Next select user from people section and click the dropdown on the right 	pane.
	->You should now see Custom roles and select Company 311
	->Finally click share.

**Comment by DanePillay-nel** [comment]
Lab 5 Exercise 1: Build notify flow
In this exercise, you create a flow that will notify the creator of a problem when the status changes.

Task 1: Create flow
In this task, you will create a flow that send notification when the status of problem report Row changes.

Navigate to https://make.powerapps.com/ and make sure you are in the correct environment.

Select Solutions and click to open the Company 311 solution.

**Click + New and select Flow.** has been renamed to **CLOUD FLOW**

![image](https://user-images.githubusercontent.com/13525534/110998825-18374b80-8388-11eb-9c30-9b3c17314d18.png)

Step 4 .Search for when a Row is created and select When a Row is created, updated, or deleted Microsoft Dataverse (Current Environment) **is incorrect.**

Please use When a row is added ,modified or deleted Common Data Service(current environment)
![image](https://user-images.githubusercontent.com/13525534/110999081-82e88700-8388-11eb-8d74-6a7215398408.png)

**Comment by DanePillay-nel** [comment]
**Lab 05: Power Automate**
Exercise 1: Build notify flow
Task 1: Create flow
Step 14: Enter internalemailaddress for **Select Query.** has been renamed to **Select Columns**

**Comment by luconsta** [comment]
I would add another typo that will cause improper functioning of the TabControl component (which still not Orange since September 2020 ;-)):

Task 3: Create the user application > Step 20: Rename the new screen **New Reports Screen**.

Shoud read **New Report Screen** (without s) because the code that will run **OnStart** is using **_Screen: 'New Report Screen'_**

**Comment by luconsta** [comment]
One other problem:

**Lab 03 > Exercise 4: Add new report > Task 1: Add new report form > Step 7: Remove the _Location_ Column**.
Then in **Step 8: Select Details, Building, _Department_, and Photo, and then click Add**

Why remove **location** and adding **department** when in the **Lab 02 > Task 4: Interview 2 Notes** is stated:

> Department should not be provided by user but assigned after submitting

.

**Comment by DanePillay-nel** [comment]
Thank you so much. Appreciate the contribution Sent from my Galaxy
-------- Original message --------From: luconsta ***@***.***> Date: 2021/03/26  17:34  (GMT+02:00) To: MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker ***@***.***> Cc: DanePillay-nel ***@***.***>, Comment ***@***.***> Subject: Re: [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker] General list of found issues in the whole labs guidance (#5) 
One other problem:
Lab 03 > Exercise 4: Add new report > Task 1: Add new report form > Step 7: Remove the Location Column.
Then in Step 8: Select Details, Building, Department, and Photo, and then click Add
Why remove location and adding department when in the Lab 02 > Task 4: Interview 2 Notes is stated:

Department should not be provided by user but assigned after submitting

.

**Comment by DZmuda-lm** [comment]
Lab 02: Data Model and Model-Driven App
Exercise 6: Import data

Import Data flow fro m the DataImport.zip is not working:

![image](https://user-images.githubusercontent.com/88529420/128467840-3a731e8b-c5b2-45ea-8032-456ece8a9100.png)

![image](https://user-images.githubusercontent.com/88529420/128468110-da39e57e-80d9-45f5-9b29-b95db0759abc.png)

**Comment by RobertRybaric** [comment]
> Lab 02: Data Model and Model-Driven App
> Exercise 6: Import data
> 
> Import Data flow fro m the DataImport.zip is not working:
> 
> ![image](https://user-images.githubusercontent.com/88529420/128467840-3a731e8b-c5b2-45ea-8032-456ece8a9100.png)
> 
> ![image](https://user-images.githubusercontent.com/88529420/128468110-da39e57e-80d9-45f5-9b29-b95db0759abc.png)

I can tell you exactly, why that import is not working: in the maker portal, there is a new modern way to create solution publishers. That new way generates a completely different prefix for the choice data, namely the value of 10.000. The result is, that the preconfigured values for the choice column to be imported do not work anymore, since they are totally different. The workaround is to correct the values, you can find them in the flow in a variable.

**Comment by DZmuda-lm** [comment]
> > Lab 02: Data Model and Model-Driven App
> > Exercise 6: Import data
> > Import Data flow fro m the DataImport.zip is not working:
> > ![image](https://user-images.githubusercontent.com/88529420/128467840-3a731e8b-c5b2-45ea-8032-456ece8a9100.png)
> > ![image](https://user-images.githubusercontent.com/88529420/128468110-da39e57e-80d9-45f5-9b29-b95db0759abc.png)
> 
> I can tell you exactly, why that import is not working: in the maker portal, there is a new modern way to create solution publishers. That new way generates a completely different prefix for the choice data, namely the value of 10.000. The result is, that the preconfigured values for the choice column to be imported do not work anymore, since they are totally different. The workaround is to correct the values, you can find them in the flow in a variable.

Thanks for the quick help!

**Comment by WigF1** [comment]
I realise you closed this issue, however, some of the issues listed in here have still not been actioned - so why close it ?
