### ISSUE TITLE
Error Creating Files

### ISSUE THREAD

**Issue by knupson** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#54]
I receive this error when running "node package.js"

Error: Command failed: pandoc /home/alejandrob/curs/Instructions/Labs/01/media/image1.png attribution.md --reference-doc=template.docx -o /home/alejandrob/curs/tmp/Instructions/PL-100_
pandoc: Cannot decode byte '\x89': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

**Comment by skulthm-ms** [comment]
Closing as we don't experience this issue. Please try again and if the issue persists please reach out again with more details if possible so we can regenerate the issue to provide a fix.
