### ISSUE TITLE
Module 3 - Lab 03

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#56]
# Module: 03
#### Step: 00

Description of issue
Labs which contains MS teams is causing a range of issues. Students were not able to START (button) inside teams any projects. They were not able to complete 3.1. This impacts lab 06.
Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review confirms this Issue.

**Comment by skulthm-ms** [comment]
Thank you for reporting. We just made updates, and this issue should be resolved now.
