### ISSUE TITLE
General List/Error Log for entire Lab

### ISSUE THREAD

**Issue by DanielMcKinney-LODS** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#6]
**Module 0:** 

-Exercise 1, Task 1, Step 2: No Context given.  "start free" item is absent.  
-Exercise 2, Task 1, Step 2(5): Trial environment is unable to be created, due to the user licenses. 
![image](https://user-images.githubusercontent.com/62155069/101792594-7e32df00-3aca-11eb-9ac7-ee43e9b3f6a5.png)

_In the same exercise/task/step the database URL input is required before saving.  There is not enough storage (1GB) allocated to the user to warrant a new database. To bypass the issues in Exercise 2, a person MS account was used to create a new environment (used in subsequent labs)._  

 **Lab 02:** 

-Exercise 2, Task 1, Step 2, and 5: Terminology update - Entity is now table. 
-Exercise 2, Task 2, Step 4, 7, and 9: Terminology update - Field is now column. 
-Exercise 3, Task 1, step 16: Terminology update - Field is now column. 
![image](https://user-images.githubusercontent.com/62155069/101794296-580e3e80-3acc-11eb-813e-2b5e1f9749e5.png)

-Exercise 3, Task 2, Step 2: The buttonhas been changed to "+ view column".
-Exercise 5, Task 1, Step 22: Image is absent from device. 
-Exercise 6, Task 2, Step 11: Save button is disabled due to the below error: 
![image](https://user-images.githubusercontent.com/62155069/101794600-a9b6c900-3acc-11eb-8c88-b82d02f9a6ce.png)

_Exercise 6, tasks 2, and 3 aborted due to this error_

**Lab 03:** 

-Exercise 1, Task 1, Step 7: Import should be completed before publishing customizations.
-Exercise 1, Task 1, Step 11: The   application can be accessed via clicking on it in the imported solution. This   was used since the "Lamna Healthcare Shared Components" app was   found in the app's section.
-Exercise 3, Task 1, Step 1: This   task is unrelated. It should read: select the gallery previously made - not   make a new gallery.

**Lab 04:** 

-Exercise 1, Task 1, Step 4: Fields has been changed to columns in a new MS update. 
-Exercise 1, Task 1, Step 6: Entity has been changed to table in a new MS update. 
-Exercise 1, Task 2, Step 20: Resolution error message is absent.  See below screenshot.  Status reason must be changed to complete for this message to show: 
![image](https://user-images.githubusercontent.com/62155069/101795486-95270080-3acd-11eb-91c8-4d72dd496f39.png)

**Lab 05:** 

-Exercise 2, Task 1, Step 4: Field has been renamed to columns. 
-Exercise 2, Task 1, Step 6: Entity has been renamed to table. 
-Exercise 2, Task 1, Step 10: "Assign to" field is absent, however "assign" is not. 
-Exercise 2, Task 3, Step 3: Typo on the word "one". 
-Exercise 3, Task 2, Step 1: Where is this supposed to start from? Additional specific instructions are needed. 
-Exercise 3, Task 1, Step 26:  This step is confusing. The location of the instructions is absent. 
-Exercise 3, Task 2, Step 29: Flow needs to be saved after editing. 

**Lab 06:**

-Exercise 2, Task 1, Step 8: Instructions are confusing, and could use some clarification. 
-Exercise 2, Task 1, Step 10(3): User interface does not match the screen shots provided via instructions: 
![image](https://user-images.githubusercontent.com/62155069/101796814-f3081800-3ace-11eb-8b68-140b11955a3c.png)

-Exercise 3, Task 2, Step 3: "Pin a live page" button is absent. 
-Exercise 3, Task 4, Step 2: Instructions are unclear, and need further clarification. 
-Exercise 3, Task 4, Step 2: Generate QR code is under the "share" tab now. 

**Lab 07:**

-Exercise 1, Task 1, Step 11: This step is confusing. A screenshot should be added. 
-Exercise 2, Task 1, Step 2: The user should be told Company 311 solutions should be selected before selecting solution checker. 
-Exercise 2, Task 1, Step 5: 1 Issue found: 
![image](https://user-images.githubusercontent.com/62155069/101797519-c43e7180-3acf-11eb-8f42-36633df942a3.png)

-Exercise 3, Task 1, Step 23: Test does not play back. Instead, the play screen was just frozen. Clicking the done button made it go back to the test screen.
-Exercise 4, Task 2, Step 1,2,3,4,5, and 6: For reasons outlined in Module 0, New environments cannot be made. Thus, the remaining steps will be carried out in the premade practice environment.
-Exercise 2, Task 1, Step 10:  The   premade practice environment returns an error (seen below) since the company   311 solutions is already  present: 
![image](https://user-images.githubusercontent.com/62155069/101797951-2bf4bc80-3ad0-11eb-886a-91403713af6c.png)

_Company   311 solution was deleted and then reimported using the previosuly exported   files in order to test subsequent lab steps._

**Comment by mreherefortea** [comment]
Hello Team:

Is there an update on this issue please? Thank you.

**Comment by mreherefortea** [comment]
Issue figured out for my reply here, please disregard my reply as Start does work.
