### ISSUE TITLE
Availability field not being detected properly 

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#64]
# Module: 03
#### Step: 13

Description of issue
Errors occur when accessing Availability column leading to app having errors and not able to run

Repro steps:

1. Follow all steps until Task 04, Step 13

![lab 03_01_task_04_step_13](https://user-images.githubusercontent.com/12806459/191139295-7ec74799-a437-4ee2-902e-3783d77f4732.png)

**Comment by skulthm-ms** [comment]
Thank you for reporting. We just made updates, and this issue should be resolved now.
