### ISSUE TITLE
Entity vs Table

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#7]
Hello Team:

It looks like some of the areas in Power Apps have have changed to Table but not all.  For example, take a look at the screenshot below: 

![image](https://user-images.githubusercontent.com/41710326/105203971-51caa380-5b09-11eb-8295-2ea57f787932.png)

In this Exercise 4: Compose model-driven application of  Lab 02: Data model and model-driven app,  they're still showing as Entity. This may be something that gets updated as well, but I wanted to let you know. Thank you for your time.

**Comment by mreherefortea** [comment]
Hello Team, in Lab 03 this was updated to "Edit Columns" I'm currently showing it as Fields: 
![image](https://user-images.githubusercontent.com/41710326/105369034-c2d09080-5bc7-11eb-8e2d-34c63a046042.png)

**Comment by mreherefortea** [comment]
Team, in Lab 04 it has been updated to Data Column but is still showing as Data Field:

![image](https://user-images.githubusercontent.com/41710326/105375861-b865c500-5bce-11eb-86e8-89193fbe196a.png)

**Comment by skulthm-ms** [comment]
Thank you @mreherefortea, this is really helpful. Unfortunately not all product terms are updated, and it seems we replaced some by mistake in the content as well.
I am going to keep this thread open for few days in case there are more terminology issues that needs to be reported. Thanks again for contributing to the accuracy of the labs.

**Comment by mreherefortea** [comment]
I appreciate your help and looking into it further. :)
