### ISSUE TITLE
Lab 4 - E3 - T2 - S16 - Flow Bot - Microsoft Teams - Post Adaptive Card in char or channel - Post in options are not displayed in English

### ISSUE THREAD

**Issue by ParameshRamki** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#78]
# Module: 4
#### Step: 16

Description of issue:  Flow Bot - Microsoft Teams - Post Adaptive Card in char or channel - Post in options are not displayed in English.
While amending the Escalate Expense Approval Flow Bot to include a method 'Send approval requests as adaptive card in Microsoft Teams', the language displayed in the Post In options are not in English.

Repro steps:

1. Lab 4 >> Exercise 3 >> Task 2 >> Step 16: While amending the Escalate Expense Approval Flow Bot to include a method 'Send approval requests as adaptive card in Microsoft Teams', the instruction is to select the 'Chat with Flow bot' in the '', however the drop-down option messages were not displayed in 'English'. 

![L4_E3_T2_S_flowbotnotenglish](https://user-images.githubusercontent.com/30195608/199716813-3df70162-9b4d-47f9-9afd-4e516a7f8fe6.png)

Following workaround has been used to resolve the issue. 
a) Select the Settings (Cog-wheel icon) from the top menu screen 
b) Select the 'Change your language' under the 'Language and time zone'. It will navigate to the 'https://myaccount.microsoft.com/settingsandprivacy/language' page.
c) Make sure 'English' is selected under the 'Display language', 'Preferred Language', 'Translate to Language', and 'Region format'.

![image](https://user-images.githubusercontent.com/30195608/199717149-72d5e09d-deb4-4a0d-ab6e-6c11fb9f8fc6.png)

If the environment has the default language setup has English (initial setup) then we might not encounter this issue.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue has been solved.
