### ISSUE TITLE
Incorrect Power FX formula Lab 3.1 Task 6 Step 10-11-12

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#80]
# Module: 3
#### Step: 10-11-12

Description of issue
The formula is still not correct after steps 10-11-12 are completed. 

The correct formula is in the screenshot. 

Credit to Attendee John A. 

![PL-100-Lab3 1_Task6-Step10-Formula-Incorrect](https://user-images.githubusercontent.com/1082625/205142267-8f141b55-5784-416f-9dec-a56188ee441d.png)

**Comment by bpmoring** [comment]
This was addressed with the most recent update. Thanks!
