### ISSUE TITLE
CurrentUser variable not available 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#81]
# Module: 03
#### Step: 00

Description of issue

During both labs when creating a Canvas App the user could not access the CurrentUser variable / object / element. 

This happened to 2 of 19 students this week. 

Repro steps:

1.
1.
1.

**Comment by bpmoring** [comment]
Thanks for your feedback. We will look into why this is occurring.
