### ISSUE TITLE
Module 5 Power Automate Lab Instructions need better clarification

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#82]
# Module: 05
#### Step: 00

Description of issue

Students complained that a great number of steps in this lab are not clear which lead to mistakes and a lot of time working to fix the resulting mistakes. 

I concur. 

Repro steps:

1.
1.
1.

**Comment by bpmoring** [comment]
Thank you for the feedback. We will work on creating clearer instructions with our next update.
