### ISSUE TITLE
Module 6 Power BI Lab Broken - Old version of Power BI still installed on VM! 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#83]
# Module: 06
#### Step: 00

Description of issue

The Power BI lab instructions are not correct with the data that the Power Query imports. 

The Table Column names are not correct. 

The Data Model relationships are not automatically created and have to be manually created. 

Ex 2 creation of new columns use column names that already exist! 

Installing Power BI takes over 15 minutes on current VM power configuration. 

Very poor demonstration of Quality Control on Microsoft's part. 

Repro steps:

1.
1.
1.

**Comment by bpmoring** [comment]
Thanks for your feedback. We will look into these issues.

**Comment by arnoldvilleneuve** [comment]
I raised this issue a while ago with one of the other PL courses as well. 
Arnold Villeneuve 613-833-0984 

    On Friday, January 6, 2023 at 02:12:46 p.m. EST, Brian Moring ***@***.***> wrote:  
 
 


Thanks for your feedback. We will look into these issues.

**Comment by bpmoring** [comment]
Do you recall the PL course number? If so, I can give the content developer a heads up.

**Comment by arnoldvilleneuve** [comment]
I reported the issue on githubGet Outlook for Android

**Comment by arnoldvilleneuve** [comment]
PL-600 and PL-100 and probably PL-200 have this same issue. The currently installed version of Power BI is V2.85 (CDS connector) and the currently available download of Power BI is V2.112 (Dataverse connector). 
![Power BI Desktop V2 85](https://user-images.githubusercontent.com/1082625/212728549-7d902d8c-0810-47fc-91cd-f5aada41bcd5.png)
![PowerBI Desktop v2 112](https://user-images.githubusercontent.com/1082625/212728576-c4e12d73-b8b4-4c8e-a057-7f16ff55d11b.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by arnoldvilleneuve** [comment]
I can't believe this issue is still open? Microsoft is allowing the quality of their MOC courses to deteriorate beyond believe. How can MCT provide a great learning experience when Microsoft provides them with poor quality training material and labs?

**Comment by ephiax20** [comment]
This is being worked on, but as you can imagine there are a number of moving parts to get this resolved. An updated VM image has been prepared.

CC @geschwei

**Comment by ephiax20** [comment]
Apologies for the frustration, the workaround is to install/update Power BI Desktop to the latest version.

**Comment by arnoldvilleneuve** [comment]
That's what we expect Microsoft to do. Not the students. 
Arnold Villeneuve 613-833-0984 

    On Thursday, August 17, 2023 at 08:51:43 a.m. EDT, Simon E ***@***.***> wrote:  
 
 


Apologies for the frustration, the workaround is to install/update Power BI Desktop to the latest version.
