### ISSUE TITLE
Github Lab and Applied Workshop material referred to in current training manual.

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#84]
# Module: 07 Day 3 and 4
## Lab/Demo: 
Day 3 8 hours Github business case lab. Please note that the lab has its own instructor manual.
Day 4 8 hours The Applied Workshop should take up this entire fourth day.

#### Step: 00

Description of issue

Repro steps:

1. Review the currently downloaded Trainer Handbook from the Download Center
1. Training Timeline states 

Day 3 8 hours Github business case lab. Please note that the lab has its own instructor manual.

***** Are you simply referring to the Instructions folder for the PL-100 Github page Labs 1 - 7 as the business case or is there another business case link to additional material referred to as the "Github business case". 

Day 4 8 hours The Applied Workshop should take up this entire fourth day.

***** Where is the link the Applied Workshop material? 

1.

**Comment by geschwei** [comment]
Thank you for your insight. I will let the Content owner know so they can review your suggestion.

**Comment by bpmoring** [comment]
@arnoldvilleneuve the Applied Workshop materials are available through the MCT download center.

**Comment by arnoldvilleneuve** [comment]
Do you have a link. Get Outlook for AndroidFrom: Brian Moring ***@***.***>Sent: Tuesday, March 21, 2023, 2:25 p.m.To: MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker ***@***.***>Cc: Arnold Villeneuve ***@***.***>; Mention ***@***.***>Subject: Re: [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker] Github Lab and Applied Workshop material referred to in current training manual. (Issue #84)
@arnoldvilleneuve the Applied Workshop materials are available through the MCT download center.

**Comment by bpmoring** [comment]
I do not have a link to the materials. They should be accessible from the same location as the content for PL-100. Here are the titles for the content. If you can't locate the content, please let me know and I will see if I can identify the issue. Thanks!
![image](https://user-images.githubusercontent.com/87440652/226710689-2fc270d3-46c2-49d8-8d0f-d9ee6a6a0ce6.png)

**Comment by arnoldvilleneuve** [comment]
Got it. It was not in my last download for some reason. All good. Thanks. 



Arnold Villeneuve 613-833-0984 

    On Tuesday, March 21, 2023 at 02:47:00 p.m. EDT, Brian Moring ***@***.***> wrote:  
 
 


I do not have a link to the materials. They should be accessible from the same location as the content for PL-100. Here are the titles for the content. If you can't locate the content, please let me know and I will see if I can identify the issue. Thanks!

**Comment by bpmoring** [comment]
Awesome!
